import 'package:flutter/material.dart';
import 'package:get/get.dart';

/// App-wide snackbar wrapper with top-center positioning and constrained width.
SnackbarController appSnackbar(
  String title,
  String message, {
  Color? colorText,
  Duration? duration = const Duration(seconds: 3),
  bool instantInit = true,
  SnackPosition? snackPosition = SnackPosition.TOP,
  Widget? titleText,
  Widget? messageText,
  Widget? icon,
  bool? shouldIconPulse,
  double? maxWidth = 400,
  EdgeInsets? margin = const EdgeInsets.only(top: 16),
  EdgeInsets? padding,
  double? borderRadius,
  Color? borderColor,
  double? borderWidth,
  Color? backgroundColor,
  Color? leftBarIndicatorColor,
  List<BoxShadow>? boxShadows,
  Gradient? backgroundGradient,
  TextButton? mainButton,
  OnTap? onTap,
  bool? isDismissible,
  bool? showProgressIndicator,
  DismissDirection? dismissDirection,
  AnimationController? progressIndicatorController,
  Color? progressIndicatorBackgroundColor,
  Animation<Color>? progressIndicatorValueColor,
  SnackStyle? snackStyle,
  Curve? forwardAnimationCurve,
  Curve? reverseAnimationCurve,
  Duration? animationDuration,
  double? barBlur,
  double? overlayBlur,
  SnackbarStatusCallback? snackbarStatus,
  Color? overlayColor,
  Form? userInputForm,
}) {
  return Get.snackbar(
    title,
    message,
    colorText: colorText,
    duration: duration,
    instantInit: instantInit,
    snackPosition: snackPosition,
    titleText: titleText,
    messageText: messageText,
    icon: icon,
    shouldIconPulse: shouldIconPulse,
    maxWidth: maxWidth,
    margin: margin,
    padding: padding,
    borderRadius: borderRadius,
    borderColor: borderColor,
    borderWidth: borderWidth,
    backgroundColor: backgroundColor,
    leftBarIndicatorColor: leftBarIndicatorColor,
    boxShadows: boxShadows,
    backgroundGradient: backgroundGradient,
    mainButton: mainButton,
    onTap: onTap,
    isDismissible: isDismissible,
    showProgressIndicator: showProgressIndicator,
    dismissDirection: dismissDirection,
    progressIndicatorController: progressIndicatorController,
    progressIndicatorBackgroundColor: progressIndicatorBackgroundColor,
    progressIndicatorValueColor: progressIndicatorValueColor,
    snackStyle: snackStyle,
    forwardAnimationCurve: forwardAnimationCurve,
    reverseAnimationCurve: reverseAnimationCurve,
    animationDuration: animationDuration,
    barBlur: barBlur,
    overlayBlur: overlayBlur,
    snackbarStatus: snackbarStatus,
    overlayColor: overlayColor,
    userInputForm: userInputForm,
  );
}
