import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../models/message_model.dart';
import '../models/student.dart';

class CommunicationController extends GetxController {
  /// All messages
  RxList<MessageModel> messages = <MessageModel>[].obs;

  /// Messages after applying the status filter
  RxList<MessageModel> filteredMessages = <MessageModel>[].obs;

  /// Currently selected message (for detail view)
  Rxn<MessageModel> selectedMessage = Rxn<MessageModel>();

  /// "" = no filter, or one of "Inbox", "Sent", "Received records", "Vaccination requests"
  var selectedStatusFilter = ''.obs;

  /// (Optional) search query if you add free‑text search
  var searchQuery = ''.obs;

  /// Pagination (if used)
  RxInt currentPage = 1.obs;
  final int itemsPerPage = 10;

  /// Fake / demo data
  final List<MessageModel> fakeMessages = [
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '1',
      studentIds: [
        Student(
          id: '8EG390J65A',
          name: 'Ahmed Khaled Ali Ibrahim',
          avatarColor: Color(0xFF1339FF),
          dateOfBirth: DateTime.parse('2010-10-02'),
          bloodType: 'O+',
          weightKg: 39.2,
          heightCm: 136,
          goToHospital: 'Cleopatra Hospital',
          firstGuardianName: 'Ronald Taylor',
          firstGuardianPhone: '(903)105-7844x138',
          firstGuardianEmail: 'ejohnson@owen-campbell.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Kevin Ramirez',
          secondGuardianPhone: '151-548-4860',
          secondGuardianEmail: 'jacksondennis@rhodes.net',
          secondGuardianStatus: 'Offline',
          city: 'North Zachary',
          street: '365 Mcclure Spring',
          zipCode: '63039',
          province: 'Delaware',
          insuranceCompany: 'Allianz',
          policyNumber: 'POL0499418',
          passportIdNumber: 'Vi36090905',
          nationality: 'Egyptian',
          nationalId: '2101013573669393',
          gender: 'Male',
          phoneNumber: '+1-743-315-1141x81905',
          email: 'scott82@mendoza.com',
        ),
        Student(
          id: '8EG3960J65A',
          name: 'Fatma Mohamed',
          avatarColor: Color(0xFF10B981),
          dateOfBirth: DateTime.parse('2011-03-15'),
          bloodType: 'A-',
          weightKg: 35.2,
          heightCm: 132,
          goToHospital: 'Ain Shams Hospital',
          firstGuardianName: 'Amine Riahi',
          firstGuardianPhone: '+21693719091',
          firstGuardianEmail: 'amine@example.com',
          firstGuardianStatus: 'Online',
          secondGuardianName: 'Sarah Ben Ali',
          secondGuardianPhone: '+21612345678',
          secondGuardianEmail: 'sarah@example.com',
          secondGuardianStatus: 'Offline',
          city: 'Tunis',
          street: '123 Rue de Marseille',
          zipCode: '1000',
          province: 'Tunis',
          insuranceCompany: 'Saham',
          policyNumber: 'POL1234567',
          passportIdNumber: 'TN987654321',
          nationality: 'Tunisian',
          nationalId: '0123456789',
          gender: 'Female',
          phoneNumber: '+21698765432',
          email: 'fatma@example.com',
        ),
      ],
      from: 'Admin',
      subject: 'Welcome to the communication module!',
      messageBody: 'This is a test message.',
      fileUrls: [],
      examination: 'General Checkup',
      dateTime: DateTime.now(),
      status: 'Sent',
    ),
    MessageModel(
      id: '2',
      studentIds: [
        // same two students...
      ],
      from: 'Admin',
      subject: 'New updates available',
      messageBody: 'Please check the latest updates in the app.',
      fileUrls: [],
      examination: 'Follow‑up Appointment',
      dateTime: DateTime.now().add(Duration(days: 1)),
      status: 'Received',
    ),
  ];
  addMessage(MessageModel message) {
    messages.add(message);
    _applyFilter(); // reapply filter after adding
  }

  @override
  void onInit() {
    super.onInit();
    // load demo data
    messages.assignAll(fakeMessages);
    // start with no filter
    filteredMessages.assignAll(messages);
    // whenever messages or selectedStatusFilter changes, reapply
    everAll([messages, selectedStatusFilter], (_) => _applyFilter());
  }

  /// Applies the selectedStatusFilter to [messages] and updates [filteredMessages].
  void _applyFilter() {
    final filter = selectedStatusFilter.value;
    final List<MessageModel> list;

    if (filter == 'Inbox') {
      list = messages.where((m) => m.status == 'Received').toList();
    } else if (filter == 'Sent') {
      list = messages.where((m) => m.status == 'Sent').toList();
    } else if (filter == 'Received records') {
      list = messages.where((m) => m.status == 'Received records').toList();
    } else if (filter == 'Vaccination requests') {
      list = messages.where((m) => m.status == 'Vaccination requests').toList();
    } else {
      // no filter
      list = messages.toList();
    }

    filteredMessages.assignAll(list);
    // clear any open detail
    selectedMessage.value = null;
  }

  int get totalPages => (filteredMessages.length / itemsPerPage)
      .ceil()
      .clamp(1, double.infinity)
      .toInt();

  /// Move to next page if possible
  void nextPage() {
    if (currentPage.value < totalPages) {
      currentPage.value++;
    }
  }

  /// Move to previous page if possible
  void previousPage() {
    if (currentPage.value > 1) {
      currentPage.value--;
    }
  }

  /// Jump to a specific page
  void goToPage(int page) {
    currentPage.value = page.clamp(1, totalPages);
  }

  /// Toggles the status filter on/off
  void toggleStatusFilter(String status) {
    if (selectedStatusFilter.value == status) {
      selectedStatusFilter.value = '';
    } else {
      selectedStatusFilter.value = status;
    }
  }

  /// Selects a message for detail view
  void selectMessage(MessageModel msg) {
    selectedMessage.value = msg;
  }

  /// (Optional) update free‑text search and reset page
  void updateSearchQuery(String query) {
    searchQuery.value = query;
    currentPage.value = 1;
  }
}
